/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInterestRateModel } from "./IInterestRateModel";
export type { IToken } from "./IToken";
export type { InterestRateModel } from "./InterestRateModel";
export type { MockERC20 } from "./MockERC20";
